# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd892815327d870f2d93d4b1dc382ec76217d439ce5e8cdfc553b74cb2ac66bb93f6627ab9c747bdf31fe6a0ac4a151646c3465addbc9d03c9a6537b29d35b4

test:
  secret_key_base: 9f9a0da3513c3a47ba0a7f18ce28a0721aa33eeb0989c45b62a75a7b54a3f8a50712335bdc494c3f32ecacb5ef209df624c8fc3db3c76290eaa3b363d7de1866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
